In [13]:
import json
import polars as pl

from utils import target_attribute

In [14]:
def collect_qwk(model_name):
    results = []

    for prompt_id in range(1, 9):
        result_per_prompt = {}
        for att in target_attribute(prompt_id):
            with open(f"./out/few_shot/{model_name}/{prompt_id}/{att}/summary.json") as f:
                summary_dict = json.load(f)
            result_per_prompt[att] = summary_dict["qwk"]
        results.append(result_per_prompt)

    return pl.DataFrame(results, orient="row")

In [22]:
collect_qwk("gemma-4-e4b-it")

shape: (8, 11)
┌──────────┬──────────┬─────────────┬────────────┬───┬──────────┬────────────┬──────────┬──────────┐
│ overall  ┆ content  ┆ organizatio ┆ word_choic ┆ … ┆ language ┆ narrativit ┆ style    ┆ voice    │
│ ---      ┆ ---      ┆ n           ┆ e          ┆   ┆ ---      ┆ y          ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ ---         ┆ ---        ┆   ┆ f64      ┆ ---        ┆ f64      ┆ f64      │
│          ┆          ┆ f64         ┆ f64        ┆   ┆          ┆ f64        ┆          ┆          │
╞══════════╪══════════╪═════════════╪════════════╪═══╪══════════╪════════════╪══════════╪══════════╡
│ 0.151319 ┆ 0.637106 ┆ 0.601871    ┆ 0.578667   ┆ … ┆ null     ┆ null       ┆ null     ┆ null     │
│ 0.605123 ┆ 0.586313 ┆ 0.528271    ┆ 0.606398   ┆ … ┆ null     ┆ null       ┆ null     ┆ null     │
│ 0.564396 ┆ 0.626225 ┆ null        ┆ null       ┆ … ┆ 0.607068 ┆ 0.628485   ┆ null     ┆ null     │
│ 0.66386  ┆ 0.595492 ┆ null        ┆ null       ┆ … ┆ 0.619272 ┆ 0.618862   ┆ null     ┆ null     │
│ 0.705455 ┆ 0.598198 ┆ null        ┆ null       ┆ … ┆ 0.613315 ┆ 0.633057   ┆ null     ┆ null     │
│ 0.767467 ┆ 0.591147 ┆ null        ┆ null       ┆ … ┆ 0.61388  ┆ 0.595729   ┆ null     ┆ null     │
│ 0.254976 ┆ 0.250542 ┆ 0.245531    ┆ null       ┆ … ┆ null     ┆ null       ┆ 0.120198 ┆ null     │
│ 0.477642 ┆ 0.123515 ┆ 0.163908    ┆ 0.095685   ┆ … ┆ null     ┆ null       ┆ null     ┆ 0.176184 │
└──────────┴──────────┴─────────────┴────────────┴───┴──────────┴────────────┴──────────┴──────────┘

In [21]:
collect_qwk("Qwen3.5-9B")

shape: (8, 11)
┌──────────┬──────────┬─────────────┬────────────┬───┬──────────┬────────────┬──────────┬──────────┐
│ overall  ┆ content  ┆ organizatio ┆ word_choic ┆ … ┆ language ┆ narrativit ┆ style    ┆ voice    │
│ ---      ┆ ---      ┆ n           ┆ e          ┆   ┆ ---      ┆ y          ┆ ---      ┆ ---      │
│ f64      ┆ f64      ┆ ---         ┆ ---        ┆   ┆ f64      ┆ ---        ┆ f64      ┆ f64      │
│          ┆          ┆ f64         ┆ f64        ┆   ┆          ┆ f64        ┆          ┆          │
╞══════════╪══════════╪═════════════╪════════════╪═══╪══════════╪════════════╪══════════╪══════════╡
│ 0.198685 ┆ 0.52096  ┆ 0.54209     ┆ 0.508351   ┆ … ┆ null     ┆ null       ┆ null     ┆ null     │
│ 0.632105 ┆ 0.610296 ┆ 0.573758    ┆ 0.590668   ┆ … ┆ null     ┆ null       ┆ null     ┆ null     │
│ 0.452028 ┆ 0.690638 ┆ null        ┆ null       ┆ … ┆ 0.445358 ┆ 0.634742   ┆ null     ┆ null     │
│ 0.714301 ┆ 0.693686 ┆ null        ┆ null       ┆ … ┆ 0.601427 ┆ 0.708726   ┆ null     ┆ null     │
│ 0.701358 ┆ 0.577977 ┆ null        ┆ null       ┆ … ┆ 0.541009 ┆ 0.579356   ┆ null     ┆ null     │
│ 0.750601 ┆ 0.700299 ┆ null        ┆ null       ┆ … ┆ 0.646451 ┆ 0.695623   ┆ null     ┆ null     │
│ 0.568082 ┆ 0.212597 ┆ 0.266335    ┆ null       ┆ … ┆ null     ┆ null       ┆ 0.120161 ┆ null     │
│ 0.412318 ┆ 0.288963 ┆ 0.351808    ┆ 0.231216   ┆ … ┆ null     ┆ null       ┆ null     ┆ 0.268595 │
└──────────┴──────────┴─────────────┴────────────┴───┴──────────┴────────────┴──────────┴──────────┘